apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: server
        image: dmitryershov/microservices-demo:v0.0.1-paymentservice
        env:
        - name: PORT
          value: "50051"
